controllers/ItemController.php
<?php

namespace app\controllers;

use app\models\Items;
use app\models\Products;
use app\models\Locals;
use app\models\User;
use app\search\ItemSearch;
use Gumlet\ImageResize;
use MongoDB\BSON\ObjectId;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;

class ItemController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'index',
                    'new',
                    'detail',
                    'update',
                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'new',
                            'detail',
                            'update',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return User::isOwner();
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    private static function newAndUpdate($model, $type, $commission): array
    {
        $validation = false;
        $model->updated_at = time();
        $model->delete = false;
        if ($model->validate()) {
            $commission = (float)$commission;
            $model->price = (float)number_format($_POST['Items']['price'], 2, '.', '');
            $model->price_final = (float)number_format(($_POST['Items']['price'] * (float)($commission == 0 ? '1' : ($commission + 1))), 2, '.', '');
            $model->_id = new ObjectID();
            $model->weighing = (int)$model['weighing'];
            $model->state = ($_POST['Items']['state'] == 1);
            switch ($type) {
                case 'new':
                    $model->created_at = time();
                    if (Items::insertItem($model)) {
                        $validation = true;
                    }
                    break;
                case 'update':
                    $update = Items::updateItem($model);
                    if ($update) {
                        $validation = true;
                    } elseif ($update == 0) {
                        $validation = true;
                    }
                    break;
            }
        }
        $model->state = $model['state'] ? 1 : 0;
        return ['model' => $model, 'validation' => $validation];
    }

    public function actionDelete()
    {
        Items::deleteItem();
        return json_encode(['code' => 1]);
    }

    public function actionDisable()
    {
        Items::stateItem(false);
        return json_encode(['code' => 1]);
    }

    public function actionEnable()
    {
        Items::stateItem(true);
        return json_encode(['code' => 1]);
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $model = Locals::findByIdUpdate($_GET['id']);
        $product = Products::findByIdOid($_GET['id'], $_GET['x']);
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', ['searchModel' => $searchModel, 'dataProvider' => $dataProvider, 'model' => $model, 'product' => $product]);
    }

    /**
     * @throws \Gumlet\ImageResizeException
     */
    public function actionNew()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $product = Products::findByIdOid($_GET['id'], $_GET['x']);
        $model = new Items();
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $coverPage = UploadedFile::getInstance($model, 'image');
            $validateImage = true;
            if ($coverPage != null) {
                $img = 'item_' . $_GET['id'] . '_' . $_GET['x'] . '_' . time();
                $path = '../web/img/products/' . $img . '.' . $coverPage->extension;
                $model->image = $img . '.' . $coverPage->extension;
            }
            if ($validateImage) {
                $result = $this->newAndUpdate($model, 'new', $local->commission);
                if ($result['validation']) {
                    if (isset($path)) {
                        $coverPage->saveAs($path);
                        $image = new ImageResize($path);
                        $image->crop(500, 500, true, ImageResize::CROPCENTER);
                        $image->save($path);
                    }
                    Yii::$app->session->setFlash('success', $_POST['Items']['name'] . ' ingresado exitosamente ');
                    return $this->redirect(['index', 'id' => $_GET['id'], 'x' => $_GET['x']]);
                } else {
                    $model = $result['model'];
                    $model->image = $_POST['Items']['image'];
                }
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local, 'product' => $product]);
    }

    /**
     * @return string
     */
    public function actionDetail(): string
    {
        $model = Items::findByIdOid($_GET['id'], $_GET['x'], $_GET['oid']);
        return $this->renderAjax('detail', ['model' => $model]);
    }

    /**
     * @throws \Gumlet\ImageResizeException
     */
    public function actionUpdate()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $product = Products::findByIdOid($_GET['id'], $_GET['x']);
        $model = Items::findByIdXOid($_GET['id'], $_GET['x'], $_GET['oid']);
        $image_back = $model['image'];
        $name = $model['name'];
        $model->state = $model['state'] ? 1 : 0;
        if ($model->load(Yii::$app->request->post())) {
            $coverPage = UploadedFile::getInstance($model, 'image');
            $validateImage = true;
            if ($coverPage != null) {
                $img = 'item_' . $_GET['id'] . '_' . $_GET['x'] . '_' . time();
                $path = '../web/img/products/' . $img . '.' . $coverPage->extension;
                $model->image = $img . '.' . $coverPage->extension;
            } else {
                $model->image = $image_back;
            }
            if ($validateImage) {
                $result = $this->newAndUpdate($model, 'update', $local->commission);
                if ($result['validation']) {
                    if (isset($path)) {
                        $coverPage->saveAs($path);
                        $image = new ImageResize($path);
                        $image->crop(500, 500, true, ImageResize::CROPCENTER);
                        $image->save($path);
                    }
                    Yii::$app->session->setFlash('info', $_POST['Items']['name'] . ' actualizado exitosamente ');
                    return $this->redirect(['index', 'id' => $_GET['id'], 'x' => $_GET['x']]);
                } else {
                    $model = $result['model'];
                    $model->image = $image_back;
                }
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local, 'name' => $name, 'product' => $product]);
    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Products;
use app\models\Locals;
use app\models\User;
use app\search\ProductSearch;
use MongoDB\BSON\ObjectId;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

class ProductController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'index',
                    'new',
                    'detail',
                    'update',
                    'delete',
                    'disable',
                    'enable',

                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'new',
                            'detail',
                            'update',
                            'delete',
                            'disable',
                            'enable',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return User::isOwner();
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    private static function newAndUpdate($model, $type): array
    {
        $validation = false;
        $model->items = [];
        $model->updated_at = time();
        $model->open_time = ((date('H', strtotime($_POST['Products']['open_time'])) * 60) + (date('i', strtotime($_POST['Products']['open_time']))));
        $model->close_time = ((date('H', strtotime($_POST['Products']['close_time'])) * 60) + (date('i', strtotime($_POST['Products']['close_time']))));
        $model->delete = false;
        if ($model->validate()) {
            $model->_id = new ObjectID();
            $model->state = ($_POST['Products']['state'] == 1);
            $model->weighing = (int)$model['weighing'];
            $model->undefined = isset($model['undefined']);
            $model->single_date = $model['single_date'] ?? '';
            $model->start_date = $model['start_date'] ?? '';
            $model->end_date = $model['end_date'] ?? '';
            $model->day_month = isset($model['day_month']) ? (int)$model['day_month'] : null;
            $model->day_week = $model['day_week'] ?? '';
            switch ($type) {
                case 'new':
                    $model->created_at = time();
                    if (Products::newProduct($model)) {
                        $validation = true;
                    }
                    break;
                case 'update':
                    $update = Products::updateProduct($model);
                    if ($update) {
                        $validation = true;
                    } elseif ($update == 0) {
                        $validation = true;
                    }
                    break;
            }
        }
        $model->open_time = gmdate('H:i', $model['open_time'] * 60);
        $model->close_time = gmdate('H:i', $model['close_time'] * 60);
        $model->state = $model['state'] ? 1 : 0;
        return ['model' => $model, 'validation' => $validation];
    }

    public function actionDelete()
    {
        Products::deleteProduct();
        return json_encode(['code' => 1]);
    }

    public function actionDisable()
    {
        Products::stateProduct(false);
        return json_encode(['code' => 1]);
    }

    public function actionEnable()
    {
        Products::stateProduct(true);
        return json_encode(['code' => 1]);
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $model = Locals::findByIdUpdate($_GET['id']);
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', ['searchModel' => $searchModel, 'dataProvider' => $dataProvider, 'model' => $model]);
    }

    public function actionNew()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $model = new Products();
        if ($model->load(Yii::$app->request->post())) {
            $result = $this->newAndUpdate($model, 'new');
            if ($result['validation']) {
                Yii::$app->session->setFlash('success', $_POST['Products']['name'] . ' ingresado exitosamente ');
                return $this->redirect(['index', 'id' => $_GET['id']]);
            } else {
                $model = $result['model'];
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local]);
    }

    /**
     * @return string
     */
    public function actionDetail(): string
    {
        $model = Products::findByIdOid($_GET['id'], $_GET['x']);
        return $this->renderAjax('detail', ['model' => $model]);
    }

    public function actionUpdate()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $model = Products::findByIdOid($_GET['id'], $_GET['x']);
        $name = $model['name'];
        $model->open_time = gmdate('H:i', $model['open_time'] * 60);
        $model->close_time = gmdate('H:i', $model['close_time'] * 60);
        $model->state = $model['state'] ? 1 : 0;
        if ($model->load(Yii::$app->request->post())) {
            $result = $this->newAndUpdate($model, 'update');
            if ($result['validation']) {
                Yii::$app->session->setFlash('info', $_POST['Products']['name'] . ' actualizado exitosamente ');
                return $this->redirect(['index', 'id' => $_GET['id']]);
            } else {
                $model = $result['model'];
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local, 'name' => $name]);
    }
}

views/item/detail.php
<?php

use app\models\Items;
use kartik\detail\DetailView;
use yii\helpers\Html;

/* @var $model Items */

?>
<div class="container-fluid">
    <?= Html::img(Yii::getAlias('@web') . '/img/products/' . $model['image'], ['width' => '100%']) ?>
    <?php try {
        echo DetailView::widget([
            'model' => $model,
            'options' => ['class' => 'bg-white'],
            'attributes' => [
                'name',
                'description',
                [
                    'attribute' => 'created_at',
                    'format' => 'html',
                    'value' => function () use ($model) {
                        return date('Y-m-d H:i:s', $model['created_at']);
                    }
                ],
                [
                    'attribute' => 'price',
                    'format' => 'html',
                    'value' => function () use ($model) {
                        return '$ ' . $model['price'];
                    }
                ],
                [
                    'attribute' => 'price_final',
                    'format' => 'html',
                    'value' => function () use ($model) {
                        return '<strong>$ ' . $model['price_final'] . '</strong>';
                    }
                ],
                [
                    'attribute' => 'updated_at',
                    'format' => 'html',
                    'value' => function () use ($model) {
                        return date('Y-m-d H:i:s', $model['updated_at']);
                    }
                ],
                'weighing',
                [
                    'attribute' => 'state',
                    'format' => 'html',
                    'value' => function () use ($model) {
                        return $model['state'] ? '<strong style="color:green">Activado</strong>' : '<strong style="color:tomato">Desactivado</strong>';
                    }
                ],
            ]
        ]);
    } catch (Exception $e) {
    }
    ?>
</div>

views/item/form.php
<?php

use app\models\Items;
use app\models\Locals;
use app\models\Products;
use kartik\file\FileInput;
use kartik\widgets\ActiveForm;
use kartik\number\NumberControl;
use kartik\select2\Select2;
use yii\helpers\Html;


/* @var $model Items */
/* @var $local Locals */
/* @var $product Products */

if (!isset($model['_id']))
    $this->title = 'Nuevo item - ' . $product['name'] . ' - ' . $local['name'];
else
    $this->title = 'Actualizar item - ' . $product['name'] . ' - ' . ($name ?? $model['name']);

$this->params['breadcrumbs'] = [['label' => 'Items', 'url' => ['index', 'id' => $_GET['id'], 'x' => $_GET['x']]], ['label' => $this->title]];

$this->params['home'] = ['index', 'id' => $_GET['id']];

$form = ActiveForm::begin(['id' => 'menu-item-new-form', 'enableClientValidation' => false]);

?>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <?php try {
                echo $form->field($model, 'image')->widget(FileInput::class, [
                    'options' => [
                        'accept' => 'image/*',
                        'multiple' => false,
//                        'minWidth' => 500, 'maxWidth' => 500, 'minHeight' => 500, 'maxHeight' => 500
                    ],
                    'pluginOptions' => [
                        'showPreview' => true,
                        'showCaption' => true,
                        'showUpload' => false,
                        'showRemove' => false,
                        'initialPreview' => [
                            $model['image'] ? Html::img(Yii::getAlias('@web') . '/img/products/' . $model['image'], ['width' => '100%']) : null
                        ],
                        'overwriteInitial' => false,
                        'allowedFileExtensions' => ['png', 'jpg', 'jpeg'],
                    ]
                ]);
            } catch (Exception $e) {
            } ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <?= $form->field($model, 'name'); ?>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12">
            <?= $form->field($model, 'description'); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <?php try {
                echo $form->field($model, 'weighing')->widget(NumberControl::class, [
                ]);
            } catch (Exception $e) {
            } ?>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <?php try {
                echo $form->field($model, 'price')->widget(NumberControl::class, [
                    'maskedInputOptions' => [
                        'prefix' => '$ '
                    ],
                ]);
            } catch (Exception $e) {
            } ?>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <?php try {
                echo $form->field($model, 'state')->widget(Select2::class, [
                    'data' => [1 => 'Activo', 0 => 'Inactivo'],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'multiple' => false,
                        'placeholder' => '',
                    ],
                    'options' => [
                        'value' => !isset($model['_id']) ? 0 : $model['state'],
                    ]
                ]);
            } catch (Exception $e) {
            } ?>
        </div>
    </div>
    <div class="row">
        <div class="col-12 text-right">
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']); ?>
        </div>
    </div>

</div>
<?php ActiveForm::end(); ?>

views/item/index.php
<?php

use app\models\Locals;
use app\models\Products;
use app\search\ItemSearch;
use kartik\grid\GridView;
use kartik\widgets\ActiveForm;
use yii\base\InvalidConfigException;
use yii\bootstrap4\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $model Locals */
/* @var $product Products */
/* @var $searchModel ItemSearch */
/* @var $dataProvider ActiveDataProvider */

$this->title = 'Items - ' . $product['name'] . ' - ' . $model['name'];

$this->params['breadcrumbs'] = [['label' => 'Productos', 'url' => ['product/index', 'id' => $_GET['id']]], ['label' => 'Agregar nuevo item', 'url' => ['item/new', 'id' => $_GET['id'], 'x' => $_GET['x']]], ['label' => $this->title]];

$this->params['home'] = ['local/index', 'id' => $_GET['id']];

Modal::begin([
    'title' => '<h3>Detalle del item</h3>',
    'id' => 'modal',
]);
echo "<div class='clearfix' id='modalContent'></div>";
Modal::end();

Pjax::begin([
    'id' => 'itemsGrid',
    'timeout' => false,
    'enablePushState' => false,
]);
?>
    <style>
        .table {
            background-color: white;
        }
    </style>
    <div class="container-fluid">
        <?php
        $form = ActiveForm::begin([
            'id' => 'menu-item-search-form',
            'action' => ['item/index', 'id' => $_GET['id'], 'x' => $_GET['x']],
            'method' => 'get',
            'options' => ['data-pjax' => true]
        ]);
        ?>
        <div class="row pl-2">
            <div class="w-75">
                <?php try {
                    echo $form->field($searchModel, 'name')->textInput()->label(false);
                } catch (InvalidConfigException $e) {
                } ?>
            </div>
            <div class="pl-1 pb-3">
                <?= Html::submitButton('<span class="fas fa-search"></span>', ['class' => 'btn btn-success']); ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
        <div class="row">
            <div class="col-12">
                <?php
                if ($dataProvider->totalCount > 0) {
                    try {
                        echo GridView::widget([
                            'dataProvider' => $dataProvider,
                            'layout' => "{pager}{summary}{items}{pager}",
                            'options' => [
                                'class' => 'table-responsive',
                            ],
                            'responsiveWrap' => false,
                            'pager' => [
                                'firstPageLabel' => 'Inicio',
                                'lastPageLabel' => 'Fin'
                            ],
                            'columns' => [
                                [
                                    'class' => 'yii\grid\SerialColumn',
                                ],
                                [
                                    'attribute' => 'name',
                                    'label' => 'Nombre'
                                ],
                                [
                                    'attribute' => 'description',
                                    'label' => 'Descripción'
                                ],
                                [
                                    'attribute' => 'price',
                                    'label' => 'Precio',
                                    'value' => function ($data) {
                                        return isset($data['price']) ? '$ ' . $data['price'] : '';
                                    }
                                ],
                                [
                                    'attribute' => 'price_final',
                                    'label' => 'Precio final',
                                    'format' => 'html',
                                    'value' => function ($data) {
                                        return isset($data['price_final']) ? '<strong>$ ' . $data['price_final'] . '</strong>' : '';
                                    }
                                ],
                                [
                                    'attribute' => 'weighing',
                                    'label' => 'Ponderación'
                                ],
                                [
                                    'attribute' => 'state',
                                    'label' => 'Estado',
                                    'format' => 'html',
                                    'value' => function ($data) {
                                        return $data['state'] ? '<strong style="color:green">Activado</strong>' : '<strong style="color:tomato">Desactivado</strong>';
                                    }
                                ],
                                [
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{view} {update} {state} {delete}',
                                    'contentOptions' => ['style' => 'width:200px; white-space:nowrap;'],
                                    'header' => 'Acciones',
                                    'buttons' => [
                                        'view' => function ($url, $model) {
                                            return HTML::button('<i class="far fa-eye"></i>', ArrayHelper::merge(['value' => 'detail?id=' . $_GET['id'] . '&oid=' . $model['_id']->__toString() . '&x=' . $_GET['x']], ['class' => 'btn btn-info _modalButton'], ['title' => Yii::t('app', 'Detalle del producto')]));
                                        },
                                        'update' => function ($url, $model) {
                                            return Html::a('<i class="far fa-edit"></i>', ['update', 'id' => $_GET['id'], 'x' => $_GET['x'], 'oid' => $model['_id']->__toString()], ['class' => 'btn btn-primary', 'title' => Yii::t('app', 'Editar producto'), 'data-pjax' => 0]);
                                        },
                                        'state' => function ($url, $model) {
                                            if ($model['state'])
                                                return HTML::button('<i class="far fa-times-circle"></i>', ArrayHelper::merge(['value' => $model['_id']->__toString()], ['class' => 'btn btn-danger _disableState'], ['title' => Yii::t('app', 'Desactivar producto')]));
                                            return HTML::button('<i class="far fa-check-circle"></i>', ArrayHelper::merge(['value' => $model['_id']->__toString()], ['class' => 'btn btn-success _enableState'], ['title' => Yii::t('app', 'Activar producto')]));
                                        },
                                        'delete' => function ($url, $model) {
                                            return HTML::button('<i class="far fa-trash-alt"></i>', ArrayHelper::merge(['value' => $model['_id']->__toString()], ['class' => 'btn btn-secondary _delete'], ['title' => Yii::t('app', 'Eliminar producto')]));
                                        },
                                    ],
                                ],
                            ]

                        ]);
                    } catch (Exception $e) {
                    }
                } else {
                    ?>
                    <div class="empty"
                         style="padding: .75rem; border: 1px solid #dee2e6; background-color: rgba(0,0,0,.05);">No se
                        encontraron resultados.
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
<?php

Pjax::end();

$urlDelete = Yii::$app->getUrlManager()->createAbsoluteUrl('item/delete');
$urlDisable = Yii::$app->getUrlManager()->createAbsoluteUrl('item/disable');
$urlEnable = Yii::$app->getUrlManager()->createAbsoluteUrl('item/enable');

$val = $_GET['id'];
$valOid = $_GET['x'];

$script = <<< JS
$(document).ready(function() {
    $('body').on('click','._delete', function(e){
        if (confirm('¿Desea ELIMINAR este item?'))
            var valX = $(this).val();
            var valId = '$val';
            var valOid = '$valOid';
            $.ajax({
                url: '$urlDelete',
                type: 'GET',
                data: {id: valId, oid: valOid, x: valX},
                dataType: 'json',
                success: function(){
                    $.pjax.reload({container: '#itemsGrid', timeout: false});            
                }
            });
        e.preventDefault();
    });
    $('body').on('click','._disableState', function(e){
        if (confirm('¿Desea DESACTIVAR este item?'))
            var valX = $(this).val();
            var valId = '$val';
            var valOid = '$valOid';
            $.ajax({
                url: '$urlDisable',
                type: 'GET',
                data: {id: valId, oid: valOid, x: valX},
                dataType: 'json',
                success: function(){
                    $.pjax.reload({container: '#itemsGrid', timeout: false});
                }
            });
        e.preventDefault();
    });
    $('body').on('click','._enableState', function(e){
        if (confirm('¿Desea ACTIVAR este item?'))
            var valX = $(this).val();
            var valId = '$val';
            var valOid = '$valOid';
            $.ajax({
                url: '$urlEnable',
                type: 'GET',
                data: {id: valId, oid: valOid, x: valX},
                dataType: 'json',
                success: function(){
                    $.pjax.reload({container: '#itemsGrid', timeout: false});
                }
            });
        e.preventDefault();
    });
});
JS;
$this->registerJs($script);