controllers/ItemController.php
<?php

namespace app\controllers;

use app\models\Items;
use app\models\Products;
use app\models\Locals;
use app\models\User;
use app\search\ItemSearch;
use Gumlet\ImageResize;
use MongoDB\BSON\ObjectId;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;

class ItemController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'index',
                    'new',
                    'detail',
                    'update',
                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'new',
                            'detail',
                            'update',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return User::isOwner();
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    private static function newAndUpdate($model, $type, $commission): array
    {
        $validation = false;
        $model->updated_at = time();
        $model->delete = false;
        if ($model->validate()) {
            $commission = (float)$commission;
            $model->price = (float)number_format($_POST['Items']['price'], 2, '.', '');
            $model->price_final = (float)number_format(($_POST['Items']['price'] * (float)($commission == 0 ? '1' : ($commission + 1))), 2, '.', '');
            $model->_id = new ObjectID();
            $model->weighing = (int)$model['weighing'];
            $model->state = ($_POST['Items']['state'] == 1);
            switch ($type) {
                case 'new':
                    $model->created_at = time();
                    if (Items::insertItem($model)) {
                        $validation = true;
                    }
                    break;
                case 'update':
                    $update = Items::updateItem($model);
                    if ($update) {
                        $validation = true;
                    } elseif ($update == 0) {
                        $validation = true;
                    }
                    break;
            }
        }
        $model->state = $model['state'] ? 1 : 0;
        return ['model' => $model, 'validation' => $validation];
    }

    public function actionDelete()
    {
        Items::deleteItem();
        return json_encode(['code' => 1]);
    }

    public function actionDisable()
    {
        Items::stateItem(false);
        return json_encode(['code' => 1]);
    }

    public function actionEnable()
    {
        Items::stateItem(true);
        return json_encode(['code' => 1]);
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $model = Locals::findByIdUpdate($_GET['id']);
        $product = Products::findByIdOid($_GET['id'], $_GET['x']);
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', ['searchModel' => $searchModel, 'dataProvider' => $dataProvider, 'model' => $model, 'product' => $product]);
    }

    /**
     * @throws \Gumlet\ImageResizeException
     */
    public function actionNew()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $product = Products::findByIdOid($_GET['id'], $_GET['x']);
        $model = new Items();
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $coverPage = UploadedFile::getInstance($model, 'image');
            $validateImage = true;
            if ($coverPage != null) {
                $img = 'item_' . $_GET['id'] . '_' . $_GET['x'] . '_' . time();
                $path = '../web/img/products/' . $img . '.' . $coverPage->extension;
                $model->image = $img . '.' . $coverPage->extension;
            }
            if ($validateImage) {
                $result = $this->newAndUpdate($model, 'new', $local->commission);
                if ($result['validation']) {
                    if (isset($path)) {
                        $coverPage->saveAs($path);
                        $image = new ImageResize($path);
                        $image->crop(500, 500, true, ImageResize::CROPCENTER);
                        $image->save($path);
                    }
                    Yii::$app->session->setFlash('success', $_POST['Items']['name'] . ' ingresado exitosamente ');
                    return $this->redirect(['index', 'id' => $_GET['id'], 'x' => $_GET['x']]);
                } else {
                    $model = $result['model'];
                    $model->image = $_POST['Items']['image'];
                }
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local, 'product' => $product]);
    }

    /**
     * @return string
     */
    public function actionDetail(): string
    {
        $model = Items::findByIdOid($_GET['id'], $_GET['x'], $_GET['oid']);
        return $this->renderAjax('detail', ['model' => $model]);
    }

    /**
     * @throws \Gumlet\ImageResizeException
     */
    public function actionUpdate()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $product = Products::findByIdOid($_GET['id'], $_GET['x']);
        $model = Items::findByIdXOid($_GET['id'], $_GET['x'], $_GET['oid']);
        $image_back = $model['image'];
        $name = $model['name'];
        $model->state = $model['state'] ? 1 : 0;
        if ($model->load(Yii::$app->request->post())) {
            $coverPage = UploadedFile::getInstance($model, 'image');
            $validateImage = true;
            if ($coverPage != null) {
                $img = 'item_' . $_GET['id'] . '_' . $_GET['x'] . '_' . time();
                $path = '../web/img/products/' . $img . '.' . $coverPage->extension;
                $model->image = $img . '.' . $coverPage->extension;
            } else {
                $model->image = $image_back;
            }
            if ($validateImage) {
                $result = $this->newAndUpdate($model, 'update', $local->commission);
                if ($result['validation']) {
                    if (isset($path)) {
                        $coverPage->saveAs($path);
                        $image = new ImageResize($path);
                        $image->crop(500, 500, true, ImageResize::CROPCENTER);
                        $image->save($path);
                    }
                    Yii::$app->session->setFlash('info', $_POST['Items']['name'] . ' actualizado exitosamente ');
                    return $this->redirect(['index', 'id' => $_GET['id'], 'x' => $_GET['x']]);
                } else {
                    $model = $result['model'];
                    $model->image = $image_back;
                }
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local, 'name' => $name, 'product' => $product]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\User;
use yii\base\Exception;
use yii\base\InvalidArgumentException;
use app\models\DeliveryBoys;
use app\models\Notifications;
use app\models\Orders;
use app\search\OrderSearch;
use Yii;
use yii\base\DynamicModel;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'logout',
                    'index',
                    'accept',
                    'reject',
                    'assign',
                    'detail',
                    'get-new-orders',
                    'update-notification',
                    'profile',
                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'get-new-orders',
                            'update-notification',
                            'profile',
                        ],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => [
                            'accept',
                            'assign',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return Orders::isOwnerOrder(); //validar con post id
                        },
                    ],
                    [
                        'actions' => [
                            'reject',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return Orders::isOwnerOrder(); //validar con post dynamic id
                        },
                    ],
                    [
                        'actions' => [
                            'detail',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return Orders::isOwnerOrder(); //validar con get id
                        },
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions(): array
    {
        if (Yii::$app->user->isGuest)
            $this->layout = 'main-info';
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', ['dataProvider' => $dataProvider, 'searchModel' => $searchModel]);
    }

    /**
     * @return Response|string
     */
    public function actionLogin()
    {
        $this->layout = 'main-info';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return Response
     */
    public function actionLogout(): Response
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionContact(): string
    {
        if (Yii::$app->user->isGuest)
            $this->layout = 'main-info';
        return $this->render('contact');
    }

    /**
     * @return string
     */
    public function actionAbout(): string
    {
        if (Yii::$app->user->isGuest)
            $this->layout = 'main-info';
        return $this->render('about');
    }

    /**
     * @return string
     */
    public function actionTnc(): string
    {
        if (Yii::$app->user->isGuest)
            $this->layout = 'main-info';
        return $this->render('tnc');
    }

    public function actionGetNewOrders()
    {
        $new = Orders::getNewOrders();
        return json_encode(['code' => count($new)]);
    }

    public function actionUpdateNotification()
    {
        Orders::updateNotification();
        return json_encode(['code' => 1]);
    }

    public function actionAccept()
    {
        $send = [];
        if (isset($_POST['id'])) {
            $id = $_POST['id'];
            $orderDetail = Orders::findByIdUpdate($id);
            Orders::updateStatus($id, 1, null, null);
            if (isset($orderDetail['firebase_token'])) {
                $noty = new Notifications();
                $body = Yii::$app->params['messages']['preparing'];
                $send = $noty->send([$orderDetail['firebase_token']], 'ORDEN: ' . $orderDetail['code'], $orderDetail['code'], 1, $orderDetail['so'], $body);
            }
        }
        return json_encode(['code' => 1, 'notification' => $send]);
    }

    public function actionReject()
    {
        $model = new DynamicModel([
            'id' => $_GET['id'],
            'reject_reason'
        ]);
        $model->addRule('reject_reason', 'required', ['message' => 'Motivo del rechazo es requerido']);
        $model->addRule('id', 'required');
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $send = [];
            if (isset($_POST['DynamicModel']['id'])) {
                $id = $_POST['DynamicModel']['id'];
                $reject_reason = $_POST['DynamicModel']['reject_reason'];
                $orderDetail = Orders::findByIdUpdate($id);
                $cash_back = ($orderDetail['payment']['method'] == 'Tarjeta' && $orderDetail['payment']['paid_out']) ? 'Su reembolso se hará entre 5 y 10 días hábiles' : '';
                Orders::updateStatus($id, 2, $reject_reason, $cash_back);
                if (isset($orderDetail['firebase_token'])) {
                    $noty = new Notifications();
                    $body = Yii::$app->params['messages']['reject'];
                    $send = $noty->send([$orderDetail['firebase_token']], 'ORDEN: ' . $orderDetail['code'], $orderDetail['code'], 2, $orderDetail['so'], $body);
                }
            }
            return json_encode(['code' => 1, 'notification' => $send]);
        }

        $modelX = Orders::findByIdUpdate($_GET['id']);
        $dataProvider = new ArrayDataProvider([
            'allModels' => $modelX['items'],
            'pagination' => [
                'pageSize' => 20
            ],
            'sort' => false,
        ]);
        return $this->renderAjax('_reject', ['model' => $model, 'modelX' => $modelX, 'dataProvider' => $dataProvider]);
    }

    public function actionAssign()
    {
        $send = [];
        $send_boy_android = [];
        $send_boy_ios = [];
        if (isset($_POST['id'])) {
            $id = $_POST['id'];
            $orderDetail = Orders::findByIdUpdate($id);
//            $localDetail = Locals::findByIdUpdate($orderDetail['local_id']);
            if (isset($orderDetail['firebase_token'])) {
                $delivery_boy = DeliveryBoys::getDeliveryBoysActive($orderDetail['city']);
                if ($delivery_boy) {
                    $tokens_delivery_boy_android = [];
                    $tokens_delivery_boy_ios = [];
                    foreach ($delivery_boy as $val) {
                        foreach ($val['firebase_tokens'] as $value) {
                            if ($value['so'] == 'android')
                                $tokens_delivery_boy_android[] = $value['token'];
                            if ($value['so'] == 'ios')
                                $tokens_delivery_boy_ios[] = $value['token'];
                        }
                    }
                    $noty = new Notifications();
//                    $body = Yii::$app->params['messages']['assignOrder'];
                    $body_boy = Yii::$app->params['messages']['deliveryBoy'];
//                    $send = $noty->send([$orderDetail['firebase_token']], 'ORDEN: ' . $orderDetail['code'], $orderDetail['code'], 2, $orderDetail['so'], $body);
                    if (count($tokens_delivery_boy_android) > 0)
                        $send_boy_android = $noty->send($tokens_delivery_boy_android, 'ORDEN: ' . $orderDetail['code'], $orderDetail['code'], 2, $orderDetail['so'], $body_boy);
                    if (count($tokens_delivery_boy_ios) > 0)
                        $send_boy_ios = $noty->send($tokens_delivery_boy_ios, 'ORDEN: ' . $orderDetail['code'], $orderDetail['code'], 2, $orderDetail['so'], $body_boy);
                    Orders::updateDeliveryBoyAssign($id, 5);
//                    DeliveryBoys::updateAll(['orders' => (int)((int)$delivery_boy['orders'] + 1)], ['_id' => $delivery_boy['_id']]);

views/site/about.php
<?php

/* @var $this yii\web\View */

$this->title = 'Acerca de nosotros';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="container-fluid">
    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>
    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */

$this->title = 'Contactos';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="container-fluid">
    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/index.php
<?php

use app\search\OrderSearch;
use hail812\adminlte3\widgets\Callout;
use kartik\grid\GridView;
use yii\bootstrap4\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

$this->title = 'Inicio';


/* @var $searchModel OrderSearch */
/* @var $dataProvider ActiveDataProvider */

Modal::begin([
    'title' => '<h3>Detalle de la orden</h3>',
    'id' => 'modal',
    'size' => 'modal-lg'
]);
echo "<div class='clearfix' id='modalContent'></div>";
Modal::end();

?>
    <style xmlns="http://www.w3.org/1999/html">
        .table {
            background-color: white;
        }
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <?php try {
                    echo Callout::widget([
                        'type' => 'info',
                        'head' => 'Bienvenido a Nubbe - Pide de todo!',
                        'body' => 'Este es el panel de control donde podrá gestionar las órdenes, agregar, actualizar y eliminar información de tus locales.'
                    ]);
                } catch (Exception $e) {
                } ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <?php try {
                    echo GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'id' => 'ordersGrid',
                        'pjax' => true,
                        'responsiveWrap' => false,
                        'layout' => "{pager}{summary}{items}{pager}",
                        'pager' => [
                            'firstPageLabel' => 'Inicio',
                            'lastPageLabel' => 'Fin'
                        ],
                        'export' => false,
                        'panel' => [
                            'type' => false,
                            'heading' => false,
                            'after' => false,
                            'before' => HTML::button('0 pedidos nuevos', ArrayHelper::merge(['value' => 'site/update-notification'], ['id' => 'newOrders', 'class' => 'btn btn-info _addNew']))
                        ],
                        'columns' => [
                            [
                                'class' => 'yii\grid\SerialColumn',
                            ],
                            [
                                'attribute' => 'code',
                                'label' => 'Código'
                            ],
                            [
                                'attribute' => 'local',
                                'label' => 'Local',
                                'format' => 'html',
                                'value' => function ($data) {
                                    return '<strong>' . $data['local']['name'] . '</strong>';
                                }
                            ],
                            [
                                'attribute' => 'created_date',
                                'label' => 'Creación',
                                'value' => 'created_date',
                            ],
                            [
                                'attribute' => 'updated_date',
                                'label' => 'Actualización',
                                'value' => 'updated_date',
                            ],
                            [
                                'attribute' => 'subtotal',
                                'filter' => false,
                                'label' => 'Total',
                                'value' => function ($data) {
                                    return '$ ' . number_format($data['subtotal'], 2, ',', '.');
                                }
                            ],
                            [
                                'class' => 'yii\grid\ActionColumn',
                                'header' => 'Acciones',
                                'template' => '{index}',
                                'contentOptions' => ['style' => 'width:100px; white-space:nowrap; text-align:center;'],
                                'buttons' => [
                                    'index' => function ($url, $model) {
                                        if ($model["status"] == '0') {
                                            //$urlReject = Yii::$app->getUrlManager()->createAbsoluteUrl(['site/reject', 'id' => $model["_id"]->__toString()]);
                                            return HTML::button('<i class="fas fa-check"></i>', ArrayHelper::merge(['value' => $model["_id"]->__toString()], ['class' => 'btn btn-success _accept'], ['title' => Yii::t('app', 'Aceptar')])) . ' ' . HTML::button('<i class="fas fa-times"></i>', ArrayHelper::merge(['value' => $model["_id"]->__toString()], ['class' => 'btn btn-danger _reject'], ['title' => Yii::t('app', 'Rechazar')]));
                                        } else if ($model["status"] == '1' || ($model["status"] == '5' && $model['delivery_boy'] == '')) {
                                            return HTML::button('<i class="fas fa-user-plus"></i>', ArrayHelper::merge(['value' => $model["_id"]->__toString()], ['class' => 'btn btn-primary _assign'], ['title' => Yii::t('app', 'Solicitar repartidor')]));// . ' ' . HTML::button('<i class="fas fa-times"></i>', ArrayHelper::merge(['value' => $model["_id"]->__toString()], ['class' => 'btn btn-danger _modalButton'], ['title' => Yii::t('app', 'Rechazar')]));
                                        } else if ($model["status"] == '3')
                                            return '<span class="btn disabled" title="Entregando" style="background-color: #9c9c9c; color: white"><i class="fas fa-spinner "></i></span>';
                                        else if ($model["status"] == '2')
                                            return '<span class="btn disabled" title="Rechazado"><i class="fas fa-times "></i></span>';
                                        else if ($model["status"] == '4')
                                            return '<span class="btn disabled" title="Entregado"><i class="fas fa-check-square"></i></span>';
                                        else if ($model["status"] == '5' && $model['delivery_boy'] != '') {
                                            return '<span class="btn disabled" title="Repartiendo" style="background-color: #9c9c9c; color: white"><i class="fas fa-motorcycle"></i></span> ';//
                                        } else
                                            return null;
                                    }
                                ],
                            ],
                            [
                                'class' => 'yii\grid\ActionColumn',
                                'header' => 'Ver',
                                'contentOptions' => ['style' => 'width:50px; white-space:nowrap;'],
                                'template' => '{detail}',
                                'buttons' => [
                                    'detail' => function ($url, $model) {
                                        return HTML::button('<i class="fas fa-info"></i>', ArrayHelper::merge(['value' => $model["_id"]->__toString()], ['class' => 'btn btn-info _detail'], ['title' => Yii::t('app', 'Detalle')]));
                                    }
                                ],
                            ],
                        ]
                    ]);
                } catch (Exception $e) {
                } ?>
            </div>
        </div>
    </div>
<?php

$urlNewOrders = Yii::$app->getUrlManager()->createAbsoluteUrl('site/get-new-orders');
$urlAccept = Yii::$app->getUrlManager()->createAbsoluteUrl('site/accept');
$urlReject = Yii::$app->getUrlManager()->createAbsoluteUrl('site/reject');
$urlDetail = Yii::$app->getUrlManager()->createAbsoluteUrl('site/detail');
$urlAssign = Yii::$app->getUrlManager()->createAbsoluteUrl('site/assign');
$urlUpdateNotification = Yii::$app->getUrlManager()->createAbsoluteUrl('site/update-notification');
$urlSong = Yii::$app->getUrlManager()->createAbsoluteUrl('song/noty.mp3');
$urlLoading = Yii::$app->getUrlManager()->createAbsoluteUrl('img/cargando.gif');
$script = <<< JS
$(document).ready(function() {
    $('body').on('click','._addNew', function(e){
        $.ajax({
            url: '$urlUpdateNotification',
            type: 'POST',
            dataType: 'json',
            success: function(data){
                if (data.code === 1){
                    $.pjax.reload({container: '#ordersGrid-pjax', timeout: false});
                    //$.pjax.reload({container: '#orderModal-pjax', timeout: false});
                }
            }
        });
        e.preventDefault();
    });
    $('body').on('click','._accept', function(e){
        if (confirm('¿Desea ACEPTAR esta orden?'))
            var val = $(this).val();
            $.ajax({
                url: '$urlAccept',
                type: 'POST',
                data: {id: val},
                dataType: 'json',
                success: function(data){
                    if (data.code === 1){
                        $.pjax.reload({container: '#ordersGrid-pjax', timeout: false});
                        //$.pjax.reload({container: '#orderModal-pjax', timeout: false});
                    }
                }
            });
        e.preventDefault();
    });
    $('body').on('click','._reject', function(e){
        var val = $(this).val();
        $.ajax({
            url: '$urlReject',
            type: 'GET',
            data: {id: val},
            beforeSend: function() {
                $('#modal').modal('show')
                    .find('#modalContent')
                    .html('<div width="100%" style="text-align: center;"><img src="$urlLoading" alt="cargando..."></div>');
            },
            success: function(data){
                $('#modal')
                    .find('#modalContent')
                    .html(data);
            }
        });
        e.preventDefault();
    });
    $('body').on('click','._detail', function(e){
        var val = $(this).val();
        $.ajax({
            url: '$urlDetail',
            type: 'GET',
            data: {id: val},
            beforeSend: function() {
                $('#modal').modal('show')
                    .find('#modalContent')
                    .html('<div width="100%" style="text-align: center;"><img src="$urlLoading" alt="cargando..."></div>');
            },
            success: function(data){
                $('#modal')
                    .find('#modalContent')
                    .html(data);
            }
        });
        e.preventDefault();
    });
    $('body').on('click','._assign', function(e){
        if (confirm('¿Desea SOLICITAR UN REPARTIDOR para esta orden?'))
            var val = $(this).val();
            $.ajax({
                url: '$urlAssign',
                type: 'POST',
                data: {id: val},
                dataType: 'json',
                success: function(data){
                    if (data.code === 1){
                        $.pjax.reload({container: '#ordersGrid-pjax', timeout: false});
                        //$.pjax.reload({container: '#orderModal-pjax', timeout: false});
                    }
                }
            });
        e.preventDefault();
    });
    // $('body').on('click','._stop_android', function(e){
    //     if (confirm('¿Desea DETENER los pedidos de TODOS los clientes?'))
    //         var val = $(this).val();
    //         $.ajax({
    //             url: val,
    //             type: 'POST',
    //             dataType: 'json',
    //             success: function(data){
    //                 console.log(data);
    //                 if (data.code === 1){
    //                     $.pjax.reload({container: '#ordersGrid-pjax', timeout: false});
    //                 }
    //             }
    //         });
    //     e.preventDefault();
    // });
    // $('body').on('click','._start_android', function(e){
    //     if (confirm('¿Desea INICIAR los pedidos de TODOS los clientes?'))
    //         var val = $(this).val();
    //         $.ajax({
    //             url: val,
    //             type: 'POST',
    //             dataType: 'json',
    //             success: function(data){
    //                 console.log(data);
    //                 if (data.code === 1){
    //                     $.pjax.reload({container: '#ordersGrid-pjax', timeout: false});
    //                 }
    //             }
    //         });
    //     e.preventDefault();
    // });
    setInterval(function() {
        $.ajax({
            url: '$urlNewOrders',
            type: 'POST',
            dataType: 'json',
            success: function(data){
                if (data.code > 0){
                    let snd = new Audio('$urlSong');
                    snd.play();
                    $('#newOrders').text(data.code + ' órdenes nuevas');
                    document.getElementById('newOrders').style.backgroundColor = '#5cb85c';
                    document.getElementById('newOrders').style.borderColor = '#5cb85c';
                    console.log(data.code);
                }
            }
        });
    },1000);
});
JS;
$this->registerJs($script);
?>