controllers/LocalController.php
<?php

namespace app\controllers;

use app\models\Schedule;
use app\models\Locals;
use app\models\User;
use Gumlet\ImageResize;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;

class LocalController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'index',
                    'schedule',
                    'update',
                    'open',
                    'close',
                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'schedule',
                            'update',
                            'open',
                            'close',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return User::isOwner();
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $model = Locals::findById($_GET['id']);
        return $this->render('index', ['model' => $model]);
    }

    public function actionOpen()
    {
        Locals::updateAll(['state' => true], ['_id' => $_GET['id']]);
        return json_encode(['code' => 1]);
    }

    public function actionClose()
    {
        Locals::updateAll(['state' => false], ['_id' => $_GET['id']]);
        return json_encode(['code' => 1]);
    }

    public function actionSchedule()
    {
        $model = Locals::findById($_GET['id']);
        $dynamicModel = new Schedule([
            'monday_open' => isset($model['schedule']['monday']['start']) ? gmdate('H:i', $model['schedule']['monday']['start'] * 60) : '',
            'monday_close' => isset($model['schedule']['monday']['end']) ? gmdate('H:i', $model['schedule']['monday']['end'] * 60) : '',
            'tuesday_open' => isset($model['schedule']['tuesday']['start']) ? gmdate('H:i', $model['schedule']['tuesday']['start'] * 60) : '',
            'tuesday_close' => isset($model['schedule']['tuesday']['end']) ? gmdate('H:i', $model['schedule']['tuesday']['end'] * 60) : '',
            'wednesday_open' => isset($model['schedule']['wednesday']['start']) ? gmdate('H:i', $model['schedule']['wednesday']['start'] * 60) : '',
            'wednesday_close' => isset($model['schedule']['wednesday']['end']) ? gmdate('H:i', $model['schedule']['wednesday']['end'] * 60) : '',
            'thursday_open' => isset($model['schedule']['thursday']['start']) ? gmdate('H:i', $model['schedule']['thursday']['start'] * 60) : '',
            'thursday_close' => isset($model['schedule']['thursday']['end']) ? gmdate('H:i', $model['schedule']['thursday']['end'] * 60) : '',
            'friday_open' => isset($model['schedule']['friday']['start']) ? gmdate('H:i', $model['schedule']['friday']['start'] * 60) : '',
            'friday_close' => isset($model['schedule']['friday']['end']) ? gmdate('H:i', $model['schedule']['friday']['end'] * 60) : '',
            'saturday_open' => isset($model['schedule']['saturday']['start']) ? gmdate('H:i', $model['schedule']['saturday']['start'] * 60) : '',
            'saturday_close' => isset($model['schedule']['saturday']['end']) ? gmdate('H:i', $model['schedule']['saturday']['end'] * 60) : '',
            'sunday_open' => isset($model['schedule']['sunday']['start']) ? gmdate('H:i', $model['schedule']['sunday']['start'] * 60) : '',
            'sunday_close' => isset($model['schedule']['sunday']['end']) ? gmdate('H:i', $model['schedule']['sunday']['end'] * 60) : ''
        ]);
        if ($dynamicModel->load(Yii::$app->request->post()) && $dynamicModel->validate()) {
            $schedule = [];
            if (strlen($_POST['Schedule']['monday_open']) > 0 && strlen($_POST['Schedule']['monday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['monday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['monday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['monday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['monday_close']))))
                ];
                $schedule['monday'] = $time;
            }
            if (strlen($_POST['Schedule']['tuesday_open']) > 0 && strlen($_POST['Schedule']['tuesday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['tuesday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['tuesday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['tuesday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['tuesday_close']))))
                ];
                $schedule['tuesday'] = $time;
            }
            if (strlen($_POST['Schedule']['wednesday_open']) > 0 && strlen($_POST['Schedule']['wednesday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['wednesday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['wednesday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['wednesday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['wednesday_close']))))
                ];
                $schedule['wednesday'] = $time;
            }
            if (strlen($_POST['Schedule']['thursday_open']) > 0 && strlen($_POST['Schedule']['thursday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['thursday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['thursday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['thursday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['thursday_close']))))
                ];
                $schedule['thursday'] = $time;
            }
            if (strlen($_POST['Schedule']['friday_open']) > 0 && strlen($_POST['Schedule']['friday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['friday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['friday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['friday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['friday_close']))))
                ];
                $schedule['friday'] = $time;
            }
            if (strlen($_POST['Schedule']['saturday_open']) > 0 && strlen($_POST['Schedule']['saturday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['saturday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['saturday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['saturday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['saturday_close']))))
                ];
                $schedule['saturday'] = $time;
            }
            if (strlen($_POST['Schedule']['sunday_open']) > 0 && strlen($_POST['Schedule']['sunday_close']) > 0) {
                $time = [
                    'start' => ((date('H', strtotime($_POST['Schedule']['sunday_open'])) * 60) + (date('i', strtotime($_POST['Schedule']['sunday_open'])))),
                    'end' => ((date('H', strtotime($_POST['Schedule']['sunday_close'])) * 60) + (date('i', strtotime($_POST['Schedule']['sunday_close']))))
                ];
                $schedule['sunday'] = $time;
            }
            $modelUpdate = Locals::findByIdUpdate($_GET['id']);
            $modelUpdate->schedule = $schedule;
            if ($modelUpdate->save()) {
                return $this->redirect(['index', 'id' => $_GET['id']]);
            }
        }
        return $this->render('schedule', ['model' => $model, 'dynamicModel' => $dynamicModel]);
    }

    /**
     * @return string
     * @throws \Gumlet\ImageResizeException
     */
    public function actionUpdate(): string
    {
        $model = Locals::findByIdUpdate($_GET['id']);
        $name = $model['name'];
        $city = $model['city'];
        if ($model->load(Yii::$app->request->post())) {
            $location['type'] = 'Point';
            $location['coordinates'] = array_map('floatval', $_POST['Locals']['location']['coordinates']);
            $model->location = $location;
            if ($model->validate()) {
                $coverPage = UploadedFile::getInstance($model, 'photo');
                if ($coverPage != null) {
                    $img = 'local_' . time();
                    $path = '../web/img/local_profile/' . $img . '.' . $coverPage->extension;
                    $model->photo = $img . '.' . $coverPage->extension;
                } else {
                    $back = Locals::findByIdUpdate($_GET['id']);
                    $model->photo = $back['photo'];
                }
                $model->name = $name;
                $model->city = $city;
                $model->updated_at = time();
                if ($model->save()) {
                    if (isset($path)) {
                        $coverPage->saveAs($path);
                        $image = new ImageResize($path);
                        $image->crop(800, 500, true, ImageResize::CROPCENTER);
                        $image->save($path);
                    }

controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Products;
use app\models\Locals;
use app\models\User;
use app\search\ProductSearch;
use MongoDB\BSON\ObjectId;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

class ProductController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'index',
                    'new',
                    'detail',
                    'update',
                    'delete',
                    'disable',
                    'enable',

                ],
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'new',
                            'detail',
                            'update',
                            'delete',
                            'disable',
                            'enable',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function () {
                            return User::isOwner();
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    private static function newAndUpdate($model, $type): array
    {
        $validation = false;
        $model->items = [];
        $model->updated_at = time();
        $model->open_time = ((date('H', strtotime($_POST['Products']['open_time'])) * 60) + (date('i', strtotime($_POST['Products']['open_time']))));
        $model->close_time = ((date('H', strtotime($_POST['Products']['close_time'])) * 60) + (date('i', strtotime($_POST['Products']['close_time']))));
        $model->delete = false;
        if ($model->validate()) {
            $model->_id = new ObjectID();
            $model->state = ($_POST['Products']['state'] == 1);
            $model->weighing = (int)$model['weighing'];
            $model->undefined = isset($model['undefined']);
            $model->single_date = $model['single_date'] ?? '';
            $model->start_date = $model['start_date'] ?? '';
            $model->end_date = $model['end_date'] ?? '';
            $model->day_month = isset($model['day_month']) ? (int)$model['day_month'] : null;
            $model->day_week = $model['day_week'] ?? '';
            switch ($type) {
                case 'new':
                    $model->created_at = time();
                    if (Products::newProduct($model)) {
                        $validation = true;
                    }
                    break;
                case 'update':
                    $update = Products::updateProduct($model);
                    if ($update) {
                        $validation = true;
                    } elseif ($update == 0) {
                        $validation = true;
                    }
                    break;
            }
        }
        $model->open_time = gmdate('H:i', $model['open_time'] * 60);
        $model->close_time = gmdate('H:i', $model['close_time'] * 60);
        $model->state = $model['state'] ? 1 : 0;
        return ['model' => $model, 'validation' => $validation];
    }

    public function actionDelete()
    {
        Products::deleteProduct();
        return json_encode(['code' => 1]);
    }

    public function actionDisable()
    {
        Products::stateProduct(false);
        return json_encode(['code' => 1]);
    }

    public function actionEnable()
    {
        Products::stateProduct(true);
        return json_encode(['code' => 1]);
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $model = Locals::findByIdUpdate($_GET['id']);
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', ['searchModel' => $searchModel, 'dataProvider' => $dataProvider, 'model' => $model]);
    }

    public function actionNew()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $model = new Products();
        if ($model->load(Yii::$app->request->post())) {
            $result = $this->newAndUpdate($model, 'new');
            if ($result['validation']) {
                Yii::$app->session->setFlash('success', $_POST['Products']['name'] . ' ingresado exitosamente ');
                return $this->redirect(['index', 'id' => $_GET['id']]);
            } else {
                $model = $result['model'];
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local]);
    }

    /**
     * @return string
     */
    public function actionDetail(): string
    {
        $model = Products::findByIdOid($_GET['id'], $_GET['x']);
        return $this->renderAjax('detail', ['model' => $model]);
    }

    public function actionUpdate()
    {
        $local = Locals::findByIdUpdate($_GET['id']);
        $model = Products::findByIdOid($_GET['id'], $_GET['x']);
        $name = $model['name'];
        $model->open_time = gmdate('H:i', $model['open_time'] * 60);
        $model->close_time = gmdate('H:i', $model['close_time'] * 60);
        $model->state = $model['state'] ? 1 : 0;
        if ($model->load(Yii::$app->request->post())) {
            $result = $this->newAndUpdate($model, 'update');
            if ($result['validation']) {
                Yii::$app->session->setFlash('info', $_POST['Products']['name'] . ' actualizado exitosamente ');
                return $this->redirect(['index', 'id' => $_GET['id']]);
            } else {
                $model = $result['model'];
            }
        }
        return $this->render('form', ['model' => $model, 'local' => $local, 'name' => $name]);
    }
}

views/local/form.php
<?php

use app\models\Locals;
use kalyabin\maplocation\SelectMapLocationAssets;
use kalyabin\maplocation\SelectMapLocationWidget;
use kartik\widgets\ActiveForm;
use kartik\widgets\FileInput;
use yii\base\InvalidConfigException;
use yii\helpers\Html;
use yii\web\JsExpression;

/* @var $model Locals */

SelectMapLocationAssets::$googleMapApiKey = Yii::$app->params['google-map-api-key'];
SelectMapLocationAssets::register($this);

$this->title = 'Actualizar - ' . $model['name'];

$this->params['breadcrumbs'] = [['label' => $this->title]];

$this->params['home'] = ['local/index', 'id' => $_GET['id']];

?>
<div class="container-fluid">
    <?php $form = ActiveForm::begin(['id' => 'registerForm', 'options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <?php try {
                echo $form->field($model, 'photo')->widget(FileInput::class, [
                    'options' => [
                        'accept' => 'image/*',
                        'multiple' => false,
                    ],
                    'pluginOptions' => [
                        'showPreview' => true,
                        'showCaption' => true,
                        'showUpload' => false,
                        'showRemove' => false,
                        'initialPreview' => [
                            $model['photo'] ? Html::img(Yii::getAlias('@web') . '/img/local_profile/' . $model['photo'], ['width' => '100%']) : null
                        ],
                        'overwriteInitial' => false
                    ]
                ]);
            } catch (Exception $e) {
            } ?>
            <?php try {
                echo $form->field($model, 'name')->textInput(['readonly' => true]);
            } catch (InvalidConfigException $e) {
            } ?>
            <?php try {
                echo $form->field($model, 'city')->textInput(['readonly' => true]);
            } catch (InvalidConfigException $e) {
            } ?>
            <?= $form->field($model, 'description'); ?>
            <?= $form->field($model, 'phone'); ?>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <?= $form->field($model, 'email'); ?>
            <?= $form->field($model, 'website'); ?>
            <?php try {
                echo $form->field($model, 'situation')->widget(SelectMapLocationWidget::class, [
                    'attributeLatitude' => 'location[coordinates][0]',
                    'attributeLongitude' => 'location[coordinates][1]',
                    'draggable' => true,
                    'googleMapApiKey' => Yii::$app->params['google-map-api-key'],
                    'jsOptions' => [
                        'onLoadMap' => new JsExpression("
                        function(map)
                        {
                            document.getElementById('locals-situation').style.display = 'none';
                            var mapOptions = {
                               center: new google.maps.LatLng( " . $model['location']['coordinates'][0] . ", " . $model['location']['coordinates'][1] . "),
                               zoom: 17,
                               panControl: true,
                               zoomControl: true,
                               mapTypeId: google.maps.MapTypeId.ROADMAP,
                           };
                           map.setOptions(mapOptions);
                        }"
                        )],
                ]);
            } catch (Exception $e) {
            } ?>
            <div class="row">
                <div class="col-12 text-right">
                    <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']); ?>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/local/index.php
<?php

use app\models\Locals;
use kartik\detail\DetailView;
use yii\bootstrap4\Modal;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $model Locals */

$this->title = $model['name'];

$this->params['breadcrumbs'] = [['label' => $this->title]];

?>
    <style>
        #map {
            height: 100%;
            width: 100%;
            min-height: 400px;
        }
    </style>
<?php
Modal::begin([
    'title' => '<h3>Imagen del local</h3>',
    'id' => 'modal',
    'size' => 'modal-sm'
]);
echo "<div class='clearfix' id='modalContent'>" . Html::img(Yii::getAlias('@web') . '/img/local_profile/' . $model['photo'], ['width' => '100%']) . "</div>";
Modal::end();

?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 pb-2">
                <?php
                echo HTML::button('<i class="fas fa-image"></i> Portada', ArrayHelper::merge(['class' => 'btn btn-primary _modalButton'], ['title' => Yii::t('app', 'Ver portada')]));
                echo '&nbsp';
                echo Html::a('<i class="fas fa-calendar-alt"></i> Horarios', ['local/schedule', 'id' => $_GET['id']], ['class' => 'btn btn-primary', 'title' => Yii::t('app', 'Ver horarios'),]);
                echo '&nbsp';
                echo Html::a('<i class="fas fa-edit"></i> Editar', ['local/update', 'id' => $_GET['id']], ['class' => 'btn btn-primary', 'title' => Yii::t('app', 'Actualizar información'),]);
                echo '&nbsp';
                echo Html::a('<i class="fas fa-list"></i> Productos', ['product/index', 'id' => $_GET['id']], ['class' => 'btn btn-primary', 'title' => Yii::t('app', 'Actualizar productos'),]);
                ?>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 pb-2 text-right">
                <?php
                if (!$model['state']) {
                    echo HTML::button('<i class="fas fa-lock-open"></i> Abrir', ArrayHelper::merge(['value' => $model['_id']], ['class' => 'btn btn-success _openButton'], ['title' => Yii::t('app', 'Abrir')]));
                } else {
                    echo HTML::button('<i class="fas fa-lock"></i> Cerrar', ArrayHelper::merge(['value' => $model['_id']], ['class' => 'btn btn-danger _closeButton'], ['title' => Yii::t('app', 'Cerrar')]));
                }
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <?php try {
                    echo DetailView::widget([
                        'model' => $model,
                        'options' => ['class' => 'bg-white'],
                        'attributes' => [
                            'name',
                            'situation',
                            [
                                'attribute' => 'created_at',
                                'format' => 'html',
                                'value' => function () use ($model) {
                                    return date('Y-m-d H:i:s', $model['created_at']);
                                }
                            ],
                            'phone',
                            'email',
                            'website',
                            'city',
                            'description',
                            'type',
                            [
                                'attribute' => 'state',
                                'format' => 'html',
                                'value' => function () use ($model) {
                                    return $model['state'] ? '<strong style="color:#00aae4">ABIERTO (de acuerdo al horario)</strong>' : '<strong style="color:tomato">CERRADO</strong>';
                                }
                            ],
                            [
                                'attribute' => 'active',
                                'format' => 'html',
                                'value' => function () use ($model) {
                                    return $model['active'] ? '<strong style="color:green">SI</strong>' : '<strong style="color:tomato">NO</strong>';
                                }
                            ]
                        ],
                    ]);
                } catch (Exception $e) {
                }
                ?>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 bg-white p-0">
                <div id="map"></div>
            </div>
        </div>
    </div>
    <script>
        function initMap() {
            let uluru = {
                lat: <?= $model['location']['coordinates'][0] ?>,
                lng: <?= $model['location']['coordinates'][1] ?>
            };
            let map = new google.maps.Map(document.getElementById('map'), {zoom: 17, center: uluru});
            let marker = new google.maps.Marker({position: uluru, map: map});
        }
    </script>

    <script defer
            src="https://maps.googleapis.com/maps/api/js?key=<?= Yii::$app->params['google-map-api-key'] ?>&callback=initMap">
    </script>
<?php

$urlOpenOne = Yii::$app->getUrlManager()->createAbsoluteUrl('local/open');
$urlCloseOne = Yii::$app->getUrlManager()->createAbsoluteUrl('local/close');
$urlHome = Yii::$app->getUrlManager()->createAbsoluteUrl('local/index');
$script = <<< JS
$(document).ready(function() {
    $('body').on('click','._openButton', function(e){
        if (confirm('¿Desea ABRIR este local?'))
            var val = $(this).val();
            $.ajax({
                url: '$urlOpenOne',
                type: 'GET',
                data: {id: val},
                dataType: 'json',
                success: function(data){
                    if (data.code === 1){
                    console.log(data);
                        location.href = '$urlHome?id='.concat(val);
                    }
                }
            });
        e.preventDefault();
    });
    $('body').on('click','._closeButton', function(e){
        if (confirm('¿Desea CERRAR este local?'))
            var val = $(this).val();
            $.ajax({
                url: '$urlCloseOne',
                type: 'GET',
                data: {id: val},
                dataType: 'json',
                success: function(data){
                    if (data.code === 1){
                        location.href = '$urlHome?id='.concat(val);
                    }
                }
            });
        e.preventDefault();
    });
});
JS;
$this->registerJs($script);
?>